### ISSUE TITLE
Fail to install miniconda with the `.sh` installer on OpenSuse (leap 42.2)

### ISSUE THREAD

**Issue by BCArg** [deto/Miniconda-Install#5]
I have downloaded the [.sh installer](https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh) and ran `bash Miniconda3-latest-Linux-x86_64.sh`

The installer did start and I agreed with the license.

Then I was asked about the installation location, which, according to the default values should be `/home/user/miniconda3`

I then got the following error message shortly after the confirmation of the installation location:

```
Miniconda3 will now be installed into this location:
/home/user/miniconda3

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

[/home/user/miniconda3] >>> 
PREFIX=/home/user/miniconda3
Unpacking payload ...
tail: cannot open ‘+9231072’ for readingtail: cannot open ‘+2’ for reading: No such file or directory
: No such file or directory
Traceback (most recent call last):
  File "tarfile.py", line 2297, in next
  File "tarfile.py", line 1093, in fromtarfile
  File "tarfile.py", line 1029, in frombuf
tarfile.EmptyHeaderError: empty header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "conda.exe.py", line 62, in <module>
  File "tarfile.py", line 1601, in open
  File "tarfile.py", line 1482, in __init__
  File "tarfile.py", line 2312, in next
tarfile.ReadError: empty file
[10278] Failed to execute script conda.exe
ERROR: could not extract tar starting at offset 000000000000018891+9231072+2
```

I am only getting this error when attempting to install on OpenSuse. The same installation method worked smoothly on Ubuntu 18.04 LTS.

I also see that the version of the `tail` program that I have in the two machines are different. If I type `tail --version` on the OpenSuse machine I get: 
```
tail (GNU coreutils) 8.16
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Paul Rubin, David MacKenzie, Ian Lance Taylor,
and Jim Meyering.
bhinckel@cr28603:~/downloads>
```

Which is quite old, whereas I get:
```
tail (GNU coreutils) 8.28
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Paul Rubin, David MacKenzie, Ian Lance Taylor,
and Jim Meyering.
```

On the Ubuntu machine.

**Comment by deto** [comment]
This sounds like an issue with the Miniconda installer itself.  The scripts I have here are just wrappers around downloading and running it.
